// 도시 카탈로그(식별·표시 메타). 데이터 의존 0 — 대용량 스팟 데이터셋(lib/mock.ts)과 분리해
// /city 등 클라이언트(cities-geo→CityMap/CityGlobe)가 419KB 스팟 데이터를 끌어오지 않게 한다.
// spotCount는 폴백값(실 카운트는 getCitySpotCounts로 오버라이드). lib/mock.ts가 re-export한다.
import { type CityId } from "./mock-constants";

export interface City {
  id: CityId;
  name: string;
  nameEn: string;
  country: string;
  spotCount: number;
  heroGrad: string;
}

export const CITIES: City[] = [
  {
    id: "tokyo",
    name: "도쿄",
    nameEn: "Tokyo",
    country: "일본",
    spotCount: 342,
    heroGrad: "linear-gradient(135deg, #FF7A85 0%, #FFC857 100%)",
  },
  {
    id: "seoul",
    name: "서울",
    nameEn: "Seoul",
    country: "한국",
    spotCount: 218,
    heroGrad: "linear-gradient(135deg, #45D6C6 0%, #5BE0D0 60%, #FFC857 100%)",
  },
  {
    id: "osaka",
    name: "오사카",
    nameEn: "Osaka",
    country: "일본",
    spotCount: 156,
    heroGrad: "linear-gradient(135deg, #E24352 0%, #FFC857 100%)",
  },
  {
    id: "kyoto",
    name: "교토",
    nameEn: "Kyoto",
    country: "일본",
    spotCount: 189,
    heroGrad: "linear-gradient(135deg, #45D6C6 0%, #FFC857 100%)",
  },
  {
    id: "fukuoka",
    name: "후쿠오카",
    nameEn: "Fukuoka",
    country: "일본",
    spotCount: 98,
    heroGrad: "linear-gradient(135deg, #FF7A85 0%, #45D6C6 100%)",
  },
  {
    id: "busan",
    name: "부산",
    nameEn: "Busan",
    country: "한국",
    spotCount: 134,
    heroGrad: "linear-gradient(135deg, #17233C 0%, #45D6C6 100%)",
  },
  {
    id: "sapporo",
    name: "삿포로",
    nameEn: "Sapporo",
    country: "일본",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #45D6C6 0%, #17233C 100%)",
  },
  {
    id: "yokohama",
    name: "요코하마",
    nameEn: "Yokohama",
    country: "일본",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FF7A85 0%, #45D6C6 100%)",
  },
  {
    id: "okinawa",
    name: "오키나와",
    nameEn: "Okinawa",
    country: "일본",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #45D6C6 0%, #FFC857 100%)",
  },
  {
    id: "nara",
    name: "나라",
    nameEn: "Nara",
    country: "일본",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FFC857 0%, #45D6C6 100%)",
  },
  {
    id: "jeju",
    name: "제주",
    nameEn: "Jeju",
    country: "한국",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #45D6C6 0%, #5BE0D0 100%)",
  },
  {
    id: "incheon",
    name: "인천",
    nameEn: "Incheon",
    country: "한국",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #17233C 0%, #45D6C6 100%)",
  },
  {
    id: "taipei",
    name: "타이베이",
    nameEn: "Taipei",
    country: "대만",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #E24352 0%, #FFC857 100%)",
  },
  {
    id: "hongkong",
    name: "홍콩",
    nameEn: "Hong Kong",
    country: "홍콩",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #17233C 0%, #E24352 100%)",
  },
  {
    id: "bangkok",
    name: "방콕",
    nameEn: "Bangkok",
    country: "태국",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FFC857 0%, #FF7A85 100%)",
  },
  {
    id: "singapore",
    name: "싱가포르",
    nameEn: "Singapore",
    country: "싱가포르",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #45D6C6 0%, #FF7A85 100%)",
  },
  {
    id: "paris",
    name: "파리",
    nameEn: "Paris",
    country: "프랑스",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FF7A85 0%, #FFC857 100%)",
  },
  {
    id: "london",
    name: "런던",
    nameEn: "London",
    country: "영국",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #17233C 0%, #45D6C6 100%)",
  },
  {
    id: "newyork",
    name: "뉴욕",
    nameEn: "New York",
    country: "미국",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #E24352 0%, #17233C 100%)",
  },
  {
    id: "barcelona",
    name: "바르셀로나",
    nameEn: "Barcelona",
    country: "스페인",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FFC857 0%, #E24352 100%)",
  },
  {
    id: "danang",
    name: "다낭",
    nameEn: "Da Nang",
    country: "베트남",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FF7A85 0%, #FFC857 100%)",
  },
  {
    id: "hanoi",
    name: "하노이",
    nameEn: "Hanoi",
    country: "베트남",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #45D6C6 0%, #17233C 100%)",
  },
  {
    id: "bali",
    name: "발리",
    nameEn: "Bali",
    country: "인도네시아",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #17233C 0%, #E24352 100%)",
  },
  {
    id: "chiangmai",
    name: "치앙마이",
    nameEn: "Chiang Mai",
    country: "태국",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FFC857 0%, #45D6C6 100%)",
  },
  {
    id: "cebu",
    name: "세부",
    nameEn: "Cebu",
    country: "필리핀",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FF7A85 0%, #E24352 100%)",
  },
  {
    id: "rome",
    name: "로마",
    nameEn: "Rome",
    country: "이탈리아",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FF7A85 0%, #FFC857 100%)",
  },
  {
    id: "venice",
    name: "베네치아",
    nameEn: "Venice",
    country: "이탈리아",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #45D6C6 0%, #17233C 100%)",
  },
  {
    id: "florence",
    name: "피렌체",
    nameEn: "Florence",
    country: "이탈리아",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #17233C 0%, #E24352 100%)",
  },
  {
    id: "berlin",
    name: "베를린",
    nameEn: "Berlin",
    country: "독일",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FFC857 0%, #45D6C6 100%)",
  },
  {
    id: "munich",
    name: "뮌헨",
    nameEn: "Munich",
    country: "독일",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FF7A85 0%, #E24352 100%)",
  },
  {
    id: "prague",
    name: "프라하",
    nameEn: "Prague",
    country: "체코",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FF7A85 0%, #FFC857 100%)",
  },
  {
    id: "amsterdam",
    name: "암스테르담",
    nameEn: "Amsterdam",
    country: "네덜란드",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #45D6C6 0%, #17233C 100%)",
  },
  {
    id: "sydney",
    name: "시드니",
    nameEn: "Sydney",
    country: "호주",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #17233C 0%, #E24352 100%)",
  },
  {
    id: "melbourne",
    name: "멜버른",
    nameEn: "Melbourne",
    country: "호주",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FFC857 0%, #45D6C6 100%)",
  },
  {
    id: "dubai",
    name: "두바이",
    nameEn: "Dubai",
    country: "아랍에미리트",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FF7A85 0%, #E24352 100%)",
  },
  {
    id: "nagoya",
    name: "나고야",
    nameEn: "Nagoya",
    country: "일본",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FF7A85 0%, #FFC857 100%)",
  },
  {
    id: "kobe",
    name: "고베",
    nameEn: "Kobe",
    country: "일본",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #45D6C6 0%, #17233C 100%)",
  },
  {
    id: "madrid",
    name: "마드리드",
    nameEn: "Madrid",
    country: "스페인",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #17233C 0%, #E24352 100%)",
  },
  {
    id: "phuket",
    name: "푸껫",
    nameEn: "Phuket",
    country: "태국",
    spotCount: 0,
    heroGrad: "linear-gradient(135deg, #FFC857 0%, #45D6C6 100%)",
  },
];
