// 웹서치로 조사한 실제 스팟(사실 메타데이터 + 출처). 이미지는 재호스팅하지 않고 그라디언트 플레이스홀더 사용.
// spot-researcher 에이전트 결과를 매핑. lib/mock.ts가 BASE와 병합해 SPOTS/WORKS/SPOT_COORDS로 노출.
import type { Spot, Work, CityId } from "./mock";

const LABEL: Record<string, string> = {
  landmark: "랜드마크",
  anime: "애니 성지",
  drama: "드라마",
  photo: "포토 스팟",
  nature: "포토 스팟",
};

// 브랜드 그라디언트 팔레트(스팟별 순환 배정 — 실 이미지 준비 전까지 임시)
const GRADS: [string, string][] = [
  [
    "linear-gradient(135deg, #FF7A85 0%, #FFC857 100%)",
    "linear-gradient(135deg, #FF7A85 0%, #E24352 100%)",
  ],
  [
    "linear-gradient(135deg, #45D6C6 0%, #17233C 100%)",
    "linear-gradient(180deg, #38C4B4 0%, #17233C 100%)",
  ],
  [
    "linear-gradient(135deg, #17233C 0%, #E24352 100%)",
    "linear-gradient(180deg, #0B1424 0%, #E24352 100%)",
  ],
  [
    "linear-gradient(135deg, #FFC857 0%, #45D6C6 100%)",
    "linear-gradient(180deg, #FFC857 0%, #45D6C6 100%)",
  ],
  [
    "linear-gradient(135deg, #E24352 0%, #FFC857 100%)",
    "linear-gradient(180deg, #17233C 0%, #E24352 100%)",
  ],
  [
    "linear-gradient(135deg, #FBEFE0 0%, #FF7A85 100%)",
    "linear-gradient(180deg, #FBEFE0 0%, #E24352 100%)",
  ],
];

interface Raw {
  id: string;
  title: string;
  city: CityId;
  category: keyof typeof LABEL;
  lat: number;
  lng: number;
  area: string;
  subject: string;
  tip: string;
  lens?: string;
  time?: string;
  workId?: string;
  scene?: string;
  verified?: Spot["verified"];
  source: string;
}

const RAW: Raw[] = [
  // ── 도쿄 · 사진 명소 / 영화 ──
  {
    id: "atago-stairs",
    title: "아타고 신사 출세의 계단",
    city: "tokyo",
    category: "photo",
    lat: 35.664789,
    lng: 139.748389,
    area: "Atago, Minato",
    subject: "86단 돌계단 위로 솟은 도쿄타워",
    tip: "계단 아래 정면에서 위를 올려다보면 계단과 도쿄타워가 겹친다. 경내 24시간 개방으로 야간 촬영 가능.",
    lens: "24-35mm",
    time: "해질녘~점등 직후",
    verified: "official",
    source: "https://www.gotokyo.org/jp/spot/465/index.html",
  },
  {
    id: "omoide-yokocho",
    title: "오모이데 요코초",
    city: "tokyo",
    category: "photo",
    lat: 35.693125,
    lng: 139.699605,
    area: "Nishi-Shinjuku",
    subject: "붉은 초롱과 야키토리 포장마차 골목",
    tip: "폭이 좁아 광각이 유리. 해가 진 뒤 초롱에 불이 들어오면 레트로 분위기가 극대화.",
    lens: "24mm 광각",
    time: "일몰 후",
    verified: "user",
    source: "https://kanko-shinjuku.jp/wifi/-/article_723.html",
  },
  {
    id: "azumabashi",
    title: "아즈마바시 (스카이트리 뷰)",
    city: "tokyo",
    category: "landmark",
    lat: 35.710015,
    lng: 139.799046,
    area: "Asakusa, Taito",
    subject: "스미다강 건너 스카이트리와 아사히 황금 오브제",
    tip: "다리 중앙에서 강·스카이트리·아사히빌딩을 한 프레임에. 점등 직후 해질녘이 가장 화려.",
    time: "일몰~야간",
    verified: "official",
    source: "https://www.gotokyo.org/jp/spot/282/index.html",
  },
  {
    id: "odaiba-seaside",
    title: "오다이바 해변공원",
    city: "tokyo",
    category: "landmark",
    lat: 35.630721,
    lng: 139.776574,
    area: "Daiba, Minato",
    subject: "백사장 너머 레인보우브리지, 맑은 날 도쿄타워",
    tip: "백사장에선 낮은 앵글로 다리 전체를, 전망데크에선 다리와 도쿄타워를 함께. 조명은 일몰 30분 후부터.",
    time: "일몰 후",
    verified: "official",
    source: "https://www.gotokyo.org/jp/spot/39/index.html",
  },
  {
    id: "tocho",
    title: "도쿄도청 전망실",
    city: "tokyo",
    category: "landmark",
    lat: 35.689244,
    lng: 139.691741,
    area: "Nishi-Shinjuku",
    subject: "서쪽 하늘에 뜨는 후지산과 신주쿠 도심",
    tip: "45층 전망실 무료 입장. 후지산은 대기 맑은 12~2월, 서쪽 창가 자리 확보.",
    lens: "100mm+ 망원",
    time: "겨울 맑은 날",
    verified: "official",
    source: "https://www.gotokyo.org/jp/spot/74/index.html",
  },
  {
    id: "roppongi-hills",
    title: "롯폰기힐즈 도쿄시티뷰",
    city: "tokyo",
    category: "landmark",
    lat: 35.660324,
    lng: 139.730031,
    area: "Roppongi, Minato",
    subject: "도쿄타워·스카이트리, 맑은 날 후지산까지 52층 파노라마",
    tip: "통유리라 렌즈를 유리에 바짝 붙이면 반사 감소. 옥상 스카이데크는 반사 없이 촬영 가능.",
    time: "황혼",
    verified: "official",
    source: "https://tcv.roppongihills.com/en/",
  },
  {
    id: "park-hyatt-bar",
    title: "파크 하얏트 도쿄 뉴욕 바",
    city: "tokyo",
    category: "drama",
    lat: 35.68568,
    lng: 139.690994,
    area: "Nishi-Shinjuku",
    subject: "52층 바 통유리 너머 신주쿠 야경",
    workId: "lost-translation",
    scene: "밥과 샬럿이 처음 마주치는 뉴욕 바 장면",
    tip: "저녁 라이브 시 커버차지. 창가 자리 예약 권장, 스마트 캐주얼.",
    time: "일몰~야간",
    verified: "user",
    source:
      "https://www.hollywoodreporter.com/lifestyle/lifestyle-news/park-hyatt-tokyo-lost-in-translation-bar-renovation-1236416080/",
  },
  // ── 도쿄 · 애니 성지 ──
  {
    id: "shin-bijutsukan",
    title: "국립신미술관",
    city: "tokyo",
    category: "anime",
    lat: 35.665312,
    lng: 139.726382,
    area: "Roppongi, Minato",
    subject: "물결 유리 외관과 2층 카페",
    workId: "kimi-no-na",
    scene: "타키와 오쿠데라 선배가 데이트하는 장면",
    tip: "1층 로비에서 물결 유리 외벽을 올려다보는 구도. 무료 구역이라 촬영 자유.",
    lens: "16-24mm 광각",
    time: "낮(자연광)",
    verified: "official",
    source: "https://www.anitabi.jp/spots/2292",
  },
  {
    id: "ochanomizu",
    title: "오차노미즈·히지리바시",
    city: "tokyo",
    category: "anime",
    lat: 35.699228,
    lng: 139.765481,
    area: "Ochanomizu, Chiyoda",
    subject: "간다강 아치교와 JR 오차노미즈역",
    workId: "suzume",
    scene: "스즈메가 도쿄 상공 미미즈를 목격하는 장면",
    tip: "다리 인도에서 강 하류 방향으로 촬영. 차도이므로 반드시 인도에서만.",
    lens: "35mm",
    time: "해질녘",
    verified: "user",
    source: "https://anime-pilgrimage.com/suzume/",
  },
  {
    id: "ushigafuchi",
    title: "우시가후치 해자",
    city: "tokyo",
    category: "anime",
    lat: 35.688889,
    lng: 139.760556,
    area: "Kitanomaru, Chiyoda",
    subject: "황거 북쪽 다야스몬~시미즈몬 해자",
    workId: "suzume",
    scene: "스즈메가 GPS로 '우시가후치' 위치를 확인하는 장면",
    tip: "다야스몬 다리 위나 야스쿠니도리 인도에서 해자 전경을. 공원 산책로를 벗어나지 말 것.",
    lens: "24-35mm",
    time: "이른 아침(수면 반사)",
    verified: "user",
    source: "https://happymackeyblog.com/suzume-back-door-tokyo/",
  },
  {
    id: "asahi-inari",
    title: "아사히 이나리 신사 (옥상)",
    city: "tokyo",
    category: "anime",
    lat: 35.671444,
    lng: 139.767167,
    area: "Ginza, Chuo",
    subject: "빌딩 옥상의 소규모 이나리 신사",
    workId: "weathering",
    scene: "히나가 '맑음 소녀'의 힘을 얻는 옥상 신사",
    tip: "저층부 입구에서 신사 표지판과 함께. 사유 건물 옥상이라 개방 시간·통행 규칙 확인.",
    lens: "35-50mm",
    time: "노을",
    verified: "reported",
    source: "https://ja.wikipedia.org/wiki/朝日稲荷神社_(東京都中央区)",
  },
  {
    id: "tabata-hill",
    title: "다바타역 남쪽 언덕길",
    city: "tokyo",
    category: "anime",
    lat: 35.738056,
    lng: 139.760833,
    area: "Tabata, Kita",
    subject: "역 남쪽 출구 언덕길",
    workId: "weathering",
    scene: "3년 후 호다카가 히나를 다시 만나러 가는 라스트신",
    tip: "언덕 아래에서 위로 촬영하면 라스트신 구도. 주택가라 도로에서만, 주민 사생활 존중.",
    lens: "50mm",
    time: "비 오는 저녁",
    verified: "user",
    source: "https://cinemarche.net/matome/tenkinoko-tabata/",
  },
  {
    id: "kamakura-koko",
    title: "가마쿠라코코마에역",
    city: "tokyo",
    category: "anime",
    lat: 35.306694,
    lng: 139.500556,
    area: "Kamakura, Kanagawa",
    subject: "플랫폼 정면 쇼난 바다와 에노시마",
    workId: "slam-dunk",
    scene: "OP 바다 앞 건널목 장면의 인근 배경",
    tip: "촬영은 플랫폼·인도 등 안전구역에서만. 건널목 위에 서서 촬영하는 행위는 사고 위험이 있어 금지.",
    lens: "35-50mm",
    time: "늦은 오후",
    verified: "official",
    source: "https://www.nikkei.com/article/DGXKZO32426380Z20C18A6H91A00/",
  },
  {
    id: "azabu-hikawa",
    title: "아자부 히카와 신사",
    city: "tokyo",
    category: "anime",
    lat: 35.652875,
    lng: 139.731068,
    area: "Moto-Azabu, Minato",
    subject: "주택가 신사 본전과 참배로",
    workId: "sailor-moon",
    scene: "레이(세일러 마스)의 '히카와 신사' 모델",
    tip: "본전 정면 계단 아래에서 촬영. 참배객이 있는 신사이므로 예의 준수.",
    lens: "35mm",
    time: "낮",
    verified: "user",
    source: "https://www.travel.co.jp/guide/article/33003/",
  },
  {
    id: "kanda-myojin",
    title: "간다 묘진 오토코자카",
    city: "tokyo",
    category: "anime",
    lat: 35.702038,
    lng: 139.767926,
    area: "Kanda, Chiyoda",
    subject: "신사 경내와 남쪽 계단(오토코자카)",
    workId: "love-live",
    scene: "토조 노조미의 본가·μ's 연습 장소",
    tip: "오토코자카 계단 아래에서 위로. 행사 시즌 혼잡하니 평일 오전 권장.",
    lens: "24-35mm",
    time: "평일 오전",
    verified: "official",
    source: "https://old.seichimap.jp/spots/97",
  },
  {
    id: "seiseki",
    title: "세이세키사쿠라가오카 로터리",
    city: "tokyo",
    category: "anime",
    lat: 35.650833,
    lng: 139.446861,
    area: "Tama, Tokyo",
    subject: "언덕 위 로터리 상점가",
    workId: "whisper",
    scene: "시즈쿠가 사는 언덕 위 로터리 상점가의 모델",
    tip: "로터리 초입에서 완만한 경사길을 따라. 저녁 조명이 영화 분위기와 유사.",
    lens: "35mm",
    time: "해질녘",
    verified: "user",
    source: "https://ghibli.jpn.org/went/seiseki-sakuragaoka/",
  },
  // ── 서울 · 사진 명소 ──
  {
    id: "changdeok-huwon",
    title: "창덕궁 후원",
    city: "seoul",
    category: "landmark",
    lat: 37.5824,
    lng: 126.9928,
    area: "Jongno-gu",
    subject: "부용지 연못과 부용정",
    tip: "해설사 동반 예약제라 한적. 부용지 앞에서 정자와 수면 반영을 함께 담는 구도.",
    lens: "35-50mm",
    time: "가을 단풍철 오전",
    verified: "official",
    source:
      "https://korean.visitkorea.or.kr/detail/rem_detail.do?cotid=ff34c101-6cb0-44b6-8ad6-8e6a155a1df6",
  },
  {
    id: "banpo-fountain",
    title: "반포한강 달빛무지개분수",
    city: "seoul",
    category: "nature",
    lat: 37.5134,
    lng: 126.9969,
    area: "Seocho-gu",
    subject: "잠수교 위 무지개분수와 한강 노을",
    tip: "분수는 4~10월 저녁 7:30부터 30분 간격. 어스름에 분수 조명과 하늘색이 함께 사는 잠수교 위 구도.",
    lens: "24-35mm",
    time: "저녁 7:30~9시",
    verified: "official",
    source: "https://hangang.seoul.go.kr/www/contents/856.do?mid=849",
  },
  {
    id: "ttukseom-sunset",
    title: "뚝섬한강공원 노을",
    city: "seoul",
    category: "nature",
    lat: 37.5303,
    lng: 127.0668,
    area: "Gwangjin-gu",
    subject: "자벌레 건물과 잔디밭 너머 노을",
    tip: "잔디광장에서 자벌레 건축물 실루엣과 노을을 함께. 일몰 30분 전 자리 선점.",
    time: "일몰 30분 전",
    verified: "user",
    source: "https://www.st-news.co.kr/news/articleView.html?idxno=14783",
  },
  {
    id: "bukchon",
    title: "북촌한옥마을",
    city: "seoul",
    category: "photo",
    lat: 37.5826,
    lng: 126.9838,
    area: "Jongno-gu",
    subject: "기와지붕 골목 사이로 보이는 남산·N서울타워",
    tip: "북촌 6·7경 사이 언덕에서 기와지붕 사이 남산타워가 겹치는 구도. 실거주지라 이른 아침 정숙 촬영.",
    lens: "35-50mm",
    time: "이른 아침",
    verified: "official",
    source: "https://opengov.seoul.go.kr/mediahub/12901453",
  },
  {
    id: "ikseon",
    title: "익선동 한옥거리",
    city: "seoul",
    category: "photo",
    lat: 37.5726,
    lng: 126.991,
    area: "Jongno-gu",
    subject: "개조 한옥 카페·소품샵의 좁은 골목",
    tip: "오후 4~5시 낮은 햇살이 기와지붕과 어우러지는 시간대. 골목이 좁아 골목 자체를 담는 구도.",
    lens: "35mm",
    time: "오후 4~5시",
    verified: "user",
    source: "https://hanok.seoul.go.kr/front/kor/town/town09.do",
  },
  {
    id: "naksan-fortress",
    title: "낙산공원 성곽 야경",
    city: "seoul",
    category: "nature",
    lat: 37.5806,
    lng: 127.0069,
    area: "Jongno-gu",
    subject: "한양도성 성곽과 서울 도심 야경",
    tip: "성곽길을 걸으며 조명 켜진 성벽 곡선과 도심 야경을 함께. 해질 무렵부터 색이 변해 장노출에 유리.",
    lens: "광각",
    time: "해질 무렵~야경",
    verified: "user",
    source: "https://mediahub.seoul.go.kr/archives/2017555",
  },
  {
    id: "lotte-skytower",
    title: "롯데월드타워 서울스카이",
    city: "seoul",
    category: "landmark",
    lat: 37.5125,
    lng: 127.1025,
    area: "Songpa-gu",
    subject: "555m 전망대에서 내려다보는 서울과 한강",
    tip: "일몰 시간대면 낮과 야경을 모두. 118층 유리바닥·120층 테라스에서 한강·남산 방향, 통유리 반사 주의.",
    lens: "표준줌+편광",
    time: "일몰",
    verified: "official",
    source:
      "https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=7e26f7f5-dde8-4eab-b2e9-42d6d37aded1",
  },
  // ── 서울 · 드라마 / 영화 ──
  {
    id: "noksapyeong-bridge",
    title: "녹사평 육교",
    city: "seoul",
    category: "drama",
    lat: 37.5343,
    lng: 126.9867,
    area: "Noksapyeong, Yongsan-gu",
    subject: "육교 위 인물 구도와 남산타워 야경 배경",
    workId: "itaewon",
    scene: "박새로이와 조이서가 녹사평역 앞 보행육교 위에서 대화하는 장면",
    tip: "해 진 직후 남산타워 조명이 켜질 때 육교 남쪽에서 인물과 타워를 한 프레임에. 차량 육교이므로 보행로 안쪽에서 촬영.",
    time: "일몰 직후",
    verified: "user",
    source: "https://www.touringwiki.com/2021/03/a25.html",
  },
  {
    id: "dwaeji-super",
    title: "돼지쌀슈퍼 (우리슈퍼)",
    city: "seoul",
    category: "drama",
    lat: 37.5585,
    lng: 126.9575,
    area: "Ahyeon-dong, Mapo-gu",
    subject: "슈퍼 외관 간판과 좁은 생활 골목",
    workId: "parasite",
    scene: "극 중 '우리슈퍼'. 기우 과외 제안·기정 복숭아 장면의 배경",
    tip: "실제 영업 중·주민 생활 골목이라 외관만 짧게. 매장 앞 장시간 점거·큰 소리 금지.",
    time: "평일 낮",
    verified: "reported",
    source: "https://mediahub.seoul.go.kr/archives/1268956",
  },
  {
    id: "jahamun-stairs",
    title: "자하문터널 계단",
    city: "seoul",
    category: "drama",
    lat: 37.5905,
    lng: 126.9645,
    area: "Cheongun-dong, Jongno-gu",
    subject: "터널 옆 긴 하강 계단",
    workId: "parasite",
    scene: "폭우 속 기택 가족이 계단을 내려가 반지하 집으로 돌아가는 장면",
    tip: "맞은편에 서울시 포토존(포스터·설명판)이 있어 구도 잡기 좋다. 우천 시 미끄러움 주의.",
    time: "우천 후 분위기 인기",
    verified: "user",
    source: "https://mediahub.seoul.go.kr/archives/1268956",
  },
  {
    id: "sky-pizza",
    title: "스카이피자 (피자시대)",
    city: "seoul",
    category: "drama",
    lat: 37.5115,
    lng: 126.941,
    area: "Noryangjin, Dongjak-gu",
    subject: "피자 박스 접기 장면의 매장 외관",
    workId: "parasite",
    scene: "극 중 '피자시대'. 기택 가족이 피자 박스를 접는 장면",
    tip: "실제 영업 중. 한 조각이라도 구매 후 짧게 촬영하는 매너. 노량진역 도보 10분, 언덕 주의.",
    time: "영업시간 내",
    verified: "user",
    source: "https://www.grandculture.net/dongjak/toc/GC08201124",
  },
  {
    id: "deoksugung-wall",
    title: "덕수궁 돌담길",
    city: "seoul",
    category: "landmark",
    lat: 37.5647,
    lng: 126.9737,
    area: "Jeong-dong, Jung-gu",
    subject: "돌담과 가로수 길",
    workId: "goblin",
    scene: "김신과 지은탁이 돌담길을 걷는 장면 등 여러 회차 배경",
    tip: "가을 은행 단풍철이 가장 붐빔. 평일 이른 아침에 인파 없이 돌담 전경. 돌담길 산책로는 상시 개방.",
    time: "이른 아침·가을 단풍철",
    verified: "official",
    source: "https://wegive.co.kr/wezine/detail/1124",
  },
  {
    id: "nodeul-island",
    title: "노들섬",
    city: "seoul",
    category: "landmark",
    lat: 37.5175,
    lng: 126.9583,
    area: "Yongsan (Han River)",
    subject: "잔디마당과 한강대교 전경",
    workId: "startup",
    scene: "극 중 스타트업 단지 '샌드박스'로 등장",
    tip: "노을~야경에 한강대교와 함께 담으면 좋다. 공연 일정과 겹치면 혼잡하니 사전 확인.",
    time: "노을~야경",
    verified: "user",
    source:
      "https://www.vice.com/ko/article/seoul-nodeul-island-sandbox-k-drama-start-up/",
  },
  {
    id: "baegun-market",
    title: "백운시장",
    city: "seoul",
    category: "drama",
    lat: 37.6478,
    lng: 127.029,
    area: "Ssangmun-dong, Dobong-gu",
    subject: "전통시장 골목과 생선가게 외관",
    workId: "squid-game",
    scene: "상우 어머니의 생선가게가 있는 쌍문동 시장",
    tip: "실제 상인 영업 중이라 매대 앞 장시간 촬영·통행 방해 금지. 쌍문역/솔밭공원역에서 도보.",
    time: "오전 장 서는 시간",
    verified: "reported",
    source: "https://mediahub.seoul.go.kr/archives/2003156",
  },
  // ── 오사카 (신규 출시 도시) ──
  {
    id: "dotonbori-glico",
    title: "도톤보리 글리코 사인",
    city: "osaka",
    category: "landmark",
    lat: 34.66905,
    lng: 135.50129,
    area: "Dotonbori, Chuo",
    subject: "도톤보리 강변의 글리코 러너 네온 사인",
    tip: "에비스바시(戎橋) 다리 위에서 사인을 정면으로. 해 진 뒤 점등되는 야간이 가장 화려. 다리 위 혼잡·소지품 주의.",
    lens: "24-35mm",
    time: "일몰 후~밤",
    verified: "official",
    source: "https://www.glico.com/jp/health/contents/glicosign/",
  },
  {
    id: "osaka-castle-tenshukaku",
    title: "오사카성 천수각",
    city: "osaka",
    category: "landmark",
    lat: 34.68678,
    lng: 135.52337,
    area: "Osaka Castle, Chuo",
    subject: "니시노마루 정원 너머로 보이는 천수각과 해자",
    tip: "니시노마루 정원(유료)에서 서쪽 구도가 대표적. 벚꽃철(3월말~4월초)엔 천수각과 벚꽃을 함께.",
    lens: "24-70mm",
    time: "늦은 오후",
    verified: "official",
    source: "https://osaka-info.jp/spot/osaka-castle-nishinomaru-garden/",
  },
  {
    id: "umeda-sky-building",
    title: "우메다 스카이빌딩 공중정원",
    city: "osaka",
    category: "landmark",
    lat: 34.70529,
    lng: 135.49048,
    area: "Oyodonaka, Kita",
    subject: "두 타워를 잇는 도넛형 공중정원 전망대 건물",
    tip: "지상 광장에서 올려다보는 로우앵글로 독특한 실루엣. 옥상 전망대에선 오사카 360도 야경.",
    lens: "16-24mm",
    time: "일몰 직후 매직아워",
    verified: "official",
    source: "https://www.skybldg.co.jp/observatory/",
  },
  {
    id: "tsutenkaku-shinsekai",
    title: "츠텐카쿠·신세카이",
    city: "osaka",
    category: "landmark",
    lat: 34.65414,
    lng: 135.50683,
    area: "Ebisuhigashi, Naniwa",
    subject: "신세카이 상점가 골목 너머로 보이는 츠텐카쿠 타워",
    tip: "통천각 혼도리 상점가 초입에서 정면으로. 쿠시카츠 간판과 함께가 대표 컷. 주말 낮은 인파 많음.",
    lens: "35-50mm",
    time: "해질녘~야간",
    verified: "official",
    source: "https://osaka-info.jp/spot/shinsekai/",
  },
  {
    id: "sumiyoshi-taisha-sorihashi",
    title: "스미요시타이샤 반바시(태고바시)",
    city: "osaka",
    category: "landmark",
    lat: 34.6128,
    lng: 135.49294,
    area: "Sumiyoshi, Sumiyoshi-ku",
    subject: "연못에 아치를 그리는 붉은 목조 태고바시",
    tip: "남쪽 연못가에서 다리와 수면 반영을 함께. 경사 급하니 다리 옆 지면에서, 다리 위 장시간 정차 금물.",
    lens: "35-50mm",
    time: "오전 순광",
    verified: "official",
    source: "https://www.sumiyoshitaisha.net/grounds/highlights.html",
  },
  {
    id: "namba-yasaka-shishiden",
    title: "난바 야사카 신사 사자머리 무대",
    city: "osaka",
    category: "landmark",
    lat: 34.66122,
    lng: 135.49669,
    area: "Motomachi, Naniwa",
    subject: "높이 12m의 거대한 사자 머리 모양 무대(獅子殿)",
    tip: "정면 광장에서 사자 입 안쪽까지 담는 로우앵글이 대표 구도. 참배객 적은 이른 아침이 한적.",
    lens: "16-24mm",
    time: "오전",
    verified: "official",
    source: "https://nambayasaka.jp/",
  },
  // ── 교토 (신규 출시 도시) ──
  {
    id: "fushimi-inari-senbon-torii",
    title: "후시미 이나리 신사 센본토리이",
    city: "kyoto",
    category: "landmark",
    lat: 34.9706,
    lng: 135.7788,
    area: "Fushimi-ku, Kyoto",
    subject: "붉은 도리이가 겹겹이 이어지는 센본토리이 터널",
    tip: "개장 직후 오전 6~7시가 인파 없는 단독 샷. 좁은 통로라 삼각대 장시간 점유 자제, 참배객 통행 배려.",
    lens: "24-35mm 광각",
    time: "이른 아침 6~8시",
    workId: "memoirs-geisha",
    scene: "어린 치요가 붉은 도리이 터널을 달리는 장면(게이샤의 추억, 2005)",
    verified: "official",
    source: "https://www.japan.travel/en/spot/1128/",
  },
  {
    id: "kiyomizu-dera-okunoin-view",
    title: "기요미즈데라 오쿠노인 전망",
    city: "kyoto",
    category: "landmark",
    lat: 34.9944,
    lng: 135.7857,
    area: "Higashiyama-ku, Kyoto",
    subject: "본당과 무대(舞台)를 정면으로 담는 전경",
    tip: "본당 맞은편 오쿠노인 회랑에서 무대 전체가 정면. 단풍철 야간 라이트업이 인기이나 좁아 혼잡, 동선 방해 금지.",
    lens: "35-50mm",
    time: "단풍철 야간 또는 이른 아침",
    verified: "official",
    source: "https://en.wikipedia.org/wiki/Kiyomizu-dera",
  },
  {
    id: "arashiyama-bamboo-grove",
    title: "아라시야마 대나무숲길",
    city: "kyoto",
    category: "nature",
    lat: 35.0169,
    lng: 135.6716,
    area: "Ukyo-ku Sagano, Kyoto",
    subject: "사가노 대나무숲 사이로 뻗은 산책로",
    tip: "오전 7~8시 개장 직후라야 인파 없는 터널 샷. 카메라를 위로 세워 대나무 사이 하늘을 배경 삼는 로우앵글.",
    lens: "16-24mm 광각",
    time: "이른 아침 7~8시",
    verified: "official",
    source: "https://www.japan.travel/en/spot/1141/",
  },
  {
    id: "kinkakuji-golden-pavilion",
    title: "킨카쿠지(금각사) 교코치 반영뷰",
    city: "kyoto",
    category: "landmark",
    lat: 35.0391,
    lng: 135.7292,
    area: "Kita-ku, Kyoto",
    subject: "금박 누각과 교코치(거울못)에 비친 반영",
    tip: "바람 없는 이른 오전 수면이 잔잔해 반영 샷이 잘 나온다. 일방통행 관람로의 지정 포토존에서 짧게.",
    lens: "24-70mm",
    time: "무풍인 이른 오전",
    verified: "official",
    source: "https://www.shokoku-ji.jp/en/kinkakuji/",
  },
  {
    id: "gion-hanamikoji-dori",
    title: "기온 하나미코지 거리",
    city: "kyoto",
    category: "drama",
    lat: 35.0023,
    lng: 135.7753,
    area: "Higashiyama-ku Gion, Kyoto",
    subject: "전통 찻집과 마치야가 늘어선 기온의 대표 골목",
    tip: "해질녘~야간 조명이 가장 분위기. 교토시 조례상 좁은 사도에서 게이코·마이코 촬영·접촉 금지 — 인물 없는 거리 풍경 위주.",
    lens: "35-50mm",
    time: "해질녘~야간",
    workId: "makanai",
    scene: "키요가 아타고 신사 부적을 받고 돌아오는 길(무희씨네 반찬집, 2화)",
    verified: "official",
    source:
      "https://ja.kyoto.travel/support/film/tourisms/film_detail/254/film",
  },
  {
    id: "kamogawa-delta",
    title: "카모가와 델타(합류부 징검돌)",
    city: "kyoto",
    category: "anime",
    lat: 35.0308,
    lng: 135.7723,
    area: "Sakyo-ku Shimogamo, Kyoto",
    subject: "카모강·타카노강이 만나는 삼각주의 거북·물떼새 모양 징검돌",
    tip: "해질녘 노을에 삼각주에서 시내 방향 구도가 인기. 젖은 징검돌은 미끄러우니 우천 직후엔 건너지 말 것.",
    lens: "24-35mm",
    time: "해질녘",
    workId: "yojouhan",
    scene:
      "오프닝 및 주인공이 반복 등장하는 삼각주 장면(다다미 넉장반 신화대계)",
    verified: "official",
    source: "https://ja.wikipedia.org/wiki/鴨川デルタ",
  },
  // ── 후쿠오카 (신규 출시 도시) ──
  {
    id: "ohori-park-nakanoshima",
    title: "오호리공원 나카노시마",
    city: "fukuoka",
    category: "drama",
    lat: 33.58609,
    lng: 130.37643,
    area: "Chuo-ku, Fukuoka",
    subject: "연못 중앙 나카노시마 섬과 붉은 우키미도(浮見堂) 정자",
    tip: "남쪽 산책로에서 나카노시마와 우키미도가 함께 보이는 각도. 이른 아침·노을이 좋고 러너·산책객 통행 배려.",
    lens: "35-50mm",
    time: "이른 아침 또는 노을",
    workId: "gisou-furin",
    scene: "위장불륜(2019 니혼TV) 1화 나카노시마 아침 데이트 장면",
    verified: "official",
    source: "https://yokanavi.com/features/180884",
  },
  {
    id: "fukuoka-tower-momochi-beach",
    title: "후쿠오카 타워",
    city: "fukuoka",
    category: "landmark",
    lat: 33.59504,
    lng: 130.35677,
    area: "Sawara-ku Momochihama, Fukuoka",
    subject: "해변 소나무 너머로 보이는 후쿠오카 타워",
    tip: "모모치 해변에서 소나무와 타워를 함께 담는 노을~블루아워가 인기. 광각으로 낮게 앉으면 모래사장 라인과 실루엣이 함께.",
    lens: "16-24mm 광각",
    time: "일몰 직후 블루아워",
    verified: "official",
    source: "https://www.fukuokatower.co.jp/viewroom/night.php",
  },
  {
    id: "dazaifu-tenmangu-honden",
    title: "다자이후 텐만구",
    city: "fukuoka",
    category: "landmark",
    lat: 33.52139,
    lng: 130.535,
    area: "Dazaifu, Fukuoka",
    subject: "참배길 타이코바시 다리 너머 혼덴(본전) 정면",
    tip: "참배객 적은 개장 직후 이른 아침에 타이코바시와 혼덴을 정면으로. 참배 공간이라 플래시·삼각대 자제, 동선 방해 금지.",
    lens: "35-50mm",
    time: "개장 직후 이른 아침",
    verified: "official",
    source: "https://www.city.dazaifu.lg.jp/site/kanko/30634.html",
  },
  {
    id: "canal-city-hakata-nadanokawa-bridge",
    title: "캐널시티 하카타",
    city: "fukuoka",
    category: "photo",
    lat: 33.58974,
    lng: 130.41059,
    area: "Hakata-ku Sumiyoshi, Fukuoka",
    subject: "파스텔톤 곡선 건물과 중앙 운하, 분수쇼",
    tip: "나다노카와바시 다리 위에서 광각으로 찍으면 곡선 건물 전체가 한 프레임에. 분수쇼 시간에 맞추되 통행 동선은 확보.",
    lens: "16-24mm 광각",
    time: "분수쇼 시간 또는 저녁 점등 후",
    verified: "official",
    source: "https://www.crossroadfukuoka.jp/spot/12311",
  },
  {
    id: "nakasu-seiryu-park-yatai",
    title: "나카스 세이류공원 포장마차 거리",
    city: "fukuoka",
    category: "photo",
    lat: 33.59212,
    lng: 130.4051,
    area: "Hakata-ku Nakasu, Fukuoka",
    subject: "나카강변 포장마차(야타이) 불빛과 나카스 네온 야경",
    tip: "후쿠하쿠데아이바시 다리·세이류공원 강변에서 포장마차 불빛과 강 건너 네온을 함께. 손님·상인 얼굴이 나오지 않게 각도를 낮춘다.",
    lens: "50-85mm",
    time: "해질 무렵~밤",
    workId: "gisou-furin",
    scene: "위장불륜(2019 니혼TV) 나카스 세이류공원 포장마차 촬영지",
    verified: "official",
    source: "https://yokanavi.com/features/180884",
  },
  {
    id: "sakurai-futamigaura-torii",
    title: "사쿠라이 후타미가우라 부부바위",
    city: "fukuoka",
    category: "nature",
    lat: 33.64047,
    lng: 130.19664,
    area: "Itoshima, Fukuoka",
    subject: "바다 위 하얀 도리이와 부부바위(夫婦岩), 시메나와 금줄",
    tip: "6월 하지 무렵 해질녘 부부바위 사이로 지는 해가 하이라이트. 바위·도리이에 접근하지 말고 밀물 시간 확인해 안전거리 유지.",
    lens: "16-24mm 광각",
    time: "일몰(하지 전후 최적)",
    verified: "official",
    source: "https://kanko-itoshima.jp/spot/sakuraihutamigaura/",
  },
  // ── 부산 (신규 출시 도시) ──
  {
    id: "gamcheon-village",
    title: "감천문화마을",
    city: "busan",
    category: "photo",
    lat: 35.0975,
    lng: 129.01,
    area: "부산 사하구 감천동",
    subject: "산비탈을 따라 계단식으로 펼쳐진 파스텔톤 지붕과 골목 전경",
    tip: "오전 역광을 피해 촬영하고, 실제 주민 거주지라 사유지·대문 안쪽은 삼가고 통행로를 막지 않는다.",
    lens: "광각",
    time: "오전 9~11시",
    verified: "official",
    source: "https://en.wikipedia.org/wiki/Gamcheon_Culture_Village",
  },
  {
    id: "haeundae-beach",
    title: "해운대 해수욕장",
    city: "busan",
    category: "nature",
    lat: 35.15855,
    lng: 129.16053,
    area: "부산 해운대구 우동",
    subject: "백사장과 마린시티 해안 스카이라인이 함께 보이는 해변 전경",
    tip: "해 질 무렵 동쪽 백사장 끝에서 마린시티 방향을 보면 노을과 고층 빌딩 실루엣을 함께 담을 수 있다.",
    lens: "표준",
    time: "일몰 전후",
    verified: "official",
    source: "https://en.wikipedia.org/wiki/Haeundae_Beach",
  },
  {
    id: "gwangalli-gwangan-bridge",
    title: "광안리·광안대교 야경",
    city: "busan",
    category: "photo",
    lat: 35.15417,
    lng: 129.12056,
    area: "부산 수영구 광안동",
    subject: "해변에서 바라본 광안대교 야간 조명 전경",
    tip: "완전히 어두워진 직후(블루아워)에 삼각대로 장노출하면 다리 조명과 하늘색이 함께 산다.",
    lens: "광각·삼각대",
    time: "일몰 후 블루아워",
    verified: "official",
    source: "https://en.wikipedia.org/wiki/Gwangan_Bridge",
  },
  {
    id: "huinnyeoul-village",
    title: "흰여울문화마을",
    city: "busan",
    category: "drama",
    lat: 35.07728,
    lng: 129.04637,
    area: "부산 영도구 영선동4가",
    subject: "절벽을 따라 늘어선 하얀 집들과 그 너머 바다 풍경",
    tip: "위쪽 전망 계단에서 내려다보면 바다와 지붕선이 함께. 좁은 골목은 주민 생활공간이므로 조용히 이동한다.",
    lens: "표준·망원",
    workId: "byeonhoin",
    scene: "영화 변호인에서 진우의 집으로 쓰인 골목(대사 벽 포토존)",
    verified: "official",
    source:
      "https://www.visitbusan.net/index.do?lang_cd=en&menuCd=DOM_000000301001001000&uc_seq=255",
  },
  {
    id: "haedong-yonggungsa",
    title: "해동용궁사",
    city: "busan",
    category: "landmark",
    lat: 35.18833,
    lng: 129.22333,
    area: "부산 기장군 기장읍",
    subject: "해안 바위 위에 세워진 사찰 전각과 일출",
    tip: "이른 아침 일출 시간에 입구 다리에서 대웅전 방향으로 찍으면 인파를 피하고 빛도 좋다.",
    lens: "광각",
    time: "일출 직후",
    verified: "official",
    source: "https://en.wikipedia.org/wiki/Haedong_Yonggungsa",
  },
  {
    id: "taejongdae",
    title: "태종대",
    city: "busan",
    category: "nature",
    lat: 35.05,
    lng: 129.08306,
    area: "부산 영도구 동삼동",
    subject: "기암절벽과 등대, 탁 트인 남해 바다 전망",
    tip: "다누비열차나 도보로 전망대까지 이동해 촬영하고, 절벽 가장자리 안전 펜스 밖으로 나가지 않는다.",
    lens: "광각",
    time: "맑은 날 오후",
    verified: "official",
    source: "https://en.wikipedia.org/wiki/Taejongdae",
  },
];

export const RESEARCH_SPOTS: Spot[] = RAW.map((r, i) => {
  const [thumbGrad, heroGrad] = GRADS[i % GRADS.length];
  return {
    id: r.id,
    title: r.title,
    subtitle: r.time ? `${r.area} · ${r.time}` : r.area,
    city: r.city,
    categoryLabel: LABEL[r.category],
    verified: r.verified ?? "user",
    thumbGrad,
    heroGrad,
    rating: (44 + (i % 6)) / 10,
    visits: 480 + i * 53,
    saves: 190 + i * 27,
    workId: r.workId ?? null,
    scene: r.scene,
    angle: "",
    lens: r.lens ?? "",
    tip: r.tip,
    source: r.source,
  };
});

export const RESEARCH_COORDS: Record<string, { lat: number; lng: number }> =
  Object.fromEntries(RAW.map((r) => [r.id, { lat: r.lat, lng: r.lng }]));

export const RESEARCH_WORKS: Work[] = [
  {
    id: "slam-dunk",
    title: "슬램덩크",
    type: "애니",
    spotCount: 1,
    progress: 0,
  },
  {
    id: "sailor-moon",
    title: "미소녀 전사 세일러문",
    type: "애니",
    spotCount: 1,
    progress: 0,
  },
  {
    id: "love-live",
    title: "러브라이브!",
    type: "애니",
    spotCount: 1,
    progress: 0,
  },
  {
    id: "whisper",
    title: "귀를 기울이면",
    type: "애니",
    spotCount: 1,
    progress: 0,
  },
  {
    id: "lost-translation",
    title: "사랑도 통역이 되나요",
    type: "영화",
    spotCount: 1,
    progress: 0,
  },
  { id: "goblin", title: "도깨비", type: "드라마", spotCount: 1, progress: 0 },
  {
    id: "startup",
    title: "스타트업",
    type: "드라마",
    spotCount: 1,
    progress: 0,
  },
  {
    id: "squid-game",
    title: "오징어 게임",
    type: "드라마",
    spotCount: 1,
    progress: 0,
  },
  // 신규 도시(오사카·교토·후쿠오카·부산) 작품
  {
    id: "memoirs-geisha",
    title: "게이샤의 추억",
    type: "영화",
    spotCount: 1,
    progress: 0,
  },
  {
    id: "makanai",
    title: "무희씨네 반찬집",
    type: "드라마",
    spotCount: 1,
    progress: 0,
  },
  {
    id: "yojouhan",
    title: "다다미 넉장반 신화대계",
    type: "애니",
    spotCount: 1,
    progress: 0,
  },
  {
    id: "gisou-furin",
    title: "위장불륜",
    type: "드라마",
    spotCount: 2,
    progress: 0,
  },
  { id: "byeonhoin", title: "변호인", type: "영화", spotCount: 1, progress: 0 },
];
