/* data.js — mock content for all screens (도쿄 + 서울 mix) */

const CITIES = [
  {
    id: 'tokyo',
    name: '도쿄',
    nameEn: 'Tokyo',
    country: '일본',
    spotCount: 342,
    heroGrad: 'linear-gradient(135deg, #FF7A85 0%, #FFC857 100%)',
    subheroGrad: 'linear-gradient(135deg, #FF5F6D 0%, #E24352 100%)',
  },
  {
    id: 'seoul',
    name: '서울',
    nameEn: 'Seoul',
    country: '한국',
    spotCount: 218,
    heroGrad: 'linear-gradient(135deg, #45D6C6 0%, #5BE0D0 60%, #FFC857 100%)',
    subheroGrad: 'linear-gradient(135deg, #38C4B4 0%, #17233C 100%)',
  },
];

const WORKS = [
  { id: 'kimi-no-na', title: '너의 이름은.', type: '애니', spotCount: 12, progress: 4 },
  { id: 'suzume', title: '스즈메의 문단속', type: '애니', spotCount: 9, progress: 1 },
  { id: 'weathering', title: '날씨의 아이', type: '애니', spotCount: 7, progress: 0 },
  { id: 'itaewon', title: '이태원 클라쓰', type: '드라마', spotCount: 8, progress: 3 },
  { id: 'parasite', title: '기생충', type: '영화', spotCount: 5, progress: 2 },
];

const SPOTS = [
  {
    id: 'mojik',
    title: '모지항에서 본 후지산',
    subtitle: 'Shizuoka · Japan · 이른 아침 6시 30분',
    city: 'tokyo',
    category: 'landmark',
    categoryLabel: '🏯 랜드마크',
    verified: 'official',
    thumbGrad: 'linear-gradient(135deg, #FF7A85 0%, #FFC857 100%)',
    heroGrad: 'linear-gradient(135deg, #FF7A85 0%, #E24352 100%)',
    rating: 4.9,
    visits: 1248,
    photos: 348,
    saves: 892,
    workId: null,
    angle: '남서쪽 22°',
    lens: '24-70mm',
    tip: '아침 안개가 걷히기 직전이 가장 아름답습니다. 후지산 능선과 크레인이 겹치지 않도록 삼각대를 60cm 낮춰서 세팅해 보세요.',
  },
  {
    id: 'suga-shrine',
    title: '스가 신사 계단',
    subtitle: 'Yotsuya · Tokyo · 오후 5시 노을',
    city: 'tokyo',
    category: 'anime',
    categoryLabel: '⛩️ 애니 성지',
    verified: 'official',
    thumbGrad: 'linear-gradient(135deg, #FFC857 0%, #FF7A85 100%)',
    heroGrad: 'linear-gradient(180deg, #E24352 0%, #FF7A85 100%)',
    rating: 4.8,
    visits: 3210,
    photos: 1421,
    saves: 2103,
    workId: 'kimi-no-na',
    scene: '#7 · 라스트씬',
    angle: '북서쪽 45°',
    lens: '35mm',
    tip: '주말은 대기 30분 이상. 평일 오후 4시 이후 방문 추천.',
  },
  {
    id: 'shibuya',
    title: '시부야 스크램블 교차로',
    subtitle: 'Shibuya · Tokyo · 야경 최적',
    city: 'tokyo',
    category: 'landmark',
    categoryLabel: '🏯 랜드마크',
    verified: 'user',
    thumbGrad: 'linear-gradient(135deg, #17233C 0%, #E24352 100%)',
    heroGrad: 'linear-gradient(180deg, #0B1424 0%, #E24352 100%)',
    rating: 4.6,
    visits: 5842,
    photos: 4210,
    saves: 3421,
    workId: null,
    angle: '2층 스타벅스에서 남쪽',
    lens: '16-35mm',
    tip: '스타벅스 2층 창가석. 신호가 빨간불로 바뀌기 15초 전이 인파 최고.',
  },
  {
    id: 'namsan',
    title: '남산 서울타워 야경',
    subtitle: 'Yongsan · Seoul · 일몰 30분 후',
    city: 'seoul',
    category: 'landmark',
    categoryLabel: '🏯 랜드마크',
    verified: 'official',
    thumbGrad: 'linear-gradient(135deg, #FF7A85 0%, #17233C 100%)',
    heroGrad: 'linear-gradient(180deg, #E24352 0%, #17233C 100%)',
    rating: 4.7,
    visits: 4210,
    photos: 2841,
    saves: 2103,
    workId: null,
    angle: '남산 산책로 전망대에서 정북',
    lens: '70-200mm',
    tip: '일몰 30분 후 하늘이 아직 남색일 때가 매직 아워. 삼각대 필수.',
  },
  {
    id: 'gyeongbok',
    title: '경복궁 근정전 계단',
    subtitle: 'Jongno · Seoul · 오전 9시 개장 직후',
    city: 'seoul',
    category: 'landmark',
    categoryLabel: '🏯 랜드마크',
    verified: 'official',
    thumbGrad: 'linear-gradient(135deg, #FBEFE0 0%, #FF7A85 100%)',
    heroGrad: 'linear-gradient(180deg, #FBEFE0 0%, #E24352 100%)',
    rating: 4.8,
    visits: 2841,
    photos: 1932,
    saves: 1421,
    workId: null,
    angle: '동쪽에서 서쪽 정면',
    lens: '35mm',
    tip: '한복 입은 방문객은 무료 입장. 개장 직후 인파 없는 15분이 골든타임.',
  },
  {
    id: 'seongsu',
    title: '성수동 붉은벽돌 골목',
    subtitle: 'Seongdong · Seoul · 오후 3시',
    city: 'seoul',
    category: 'photo',
    categoryLabel: '✨ 포토 스팟',
    verified: 'user',
    thumbGrad: 'linear-gradient(135deg, #FF5F6D 0%, #FBEFE0 100%)',
    heroGrad: 'linear-gradient(180deg, #FF7A85 0%, #FBEFE0 100%)',
    rating: 4.5,
    visits: 1240,
    photos: 892,
    saves: 621,
    workId: null,
    angle: '골목 초입에서 안쪽',
    lens: '50mm',
    tip: '역광을 등지고 인물 촬영. 벽돌색이 살아나는 오후 3시가 베스트.',
  },
  {
    id: 'itaewon-danbam',
    title: '이태원 단밤 포차 앞',
    subtitle: 'Yongsan · Seoul · 저녁',
    city: 'seoul',
    category: 'drama',
    categoryLabel: '🎬 드라마',
    verified: 'user',
    thumbGrad: 'linear-gradient(135deg, #E24352 0%, #FFC857 100%)',
    heroGrad: 'linear-gradient(180deg, #17233C 0%, #E24352 100%)',
    rating: 4.4,
    visits: 892,
    photos: 421,
    saves: 342,
    workId: 'itaewon',
    scene: '#4 · 새로이 오프닝',
    angle: '건너편 인도에서',
    lens: '35mm',
    tip: '해가 완전히 진 후 간판 네온이 켜지면 가장 예뻐요.',
  },
  {
    id: 'harajuku',
    title: '하라주쿠 다케시타 거리',
    subtitle: 'Shibuya · Tokyo · 낮',
    city: 'tokyo',
    category: 'photo',
    categoryLabel: '✨ 포토 스팟',
    verified: 'user',
    thumbGrad: 'linear-gradient(135deg, #FFC857 0%, #45D6C6 100%)',
    heroGrad: 'linear-gradient(180deg, #FFC857 0%, #45D6C6 100%)',
    rating: 4.3,
    visits: 3421,
    photos: 2103,
    saves: 1892,
    workId: null,
    angle: '입구 아치 정면',
    lens: '24mm',
    tip: '평일 오전이 사람 적음. 컬러풀한 간판이 배경.',
  },
];

const COLLECTIONS = [
  {
    id: 'tokyo-3d4n',
    title: '도쿄 3박4일 사진 여행',
    subtitle: '10개 스팟 · 지민',
    itemCount: 10,
    coverGrad: 'linear-gradient(135deg, #FF7A85 0%, #FFC857 100%)',
    isOwn: true,
    isOfficial: false,
    spots: ['mojik', 'suga-shrine', 'shibuya', 'harajuku'],
  },
  {
    id: 'anime-pilgrimage',
    title: '너의 이름은. 성지순례 완전판',
    subtitle: '12개 스팟 · 공식',
    itemCount: 12,
    coverGrad: 'linear-gradient(135deg, #E24352 0%, #FF7A85 100%)',
    isOwn: false,
    isOfficial: true,
    spots: ['suga-shrine'],
  },
  {
    id: 'seoul-golden',
    title: '서울 골든아워 명소',
    subtitle: '8개 스팟 · 공식',
    itemCount: 8,
    coverGrad: 'linear-gradient(135deg, #FFC857 0%, #E24352 100%)',
    isOwn: false,
    isOfficial: true,
    spots: ['namsan', 'seongsu'],
  },
  {
    id: 'my-seoul',
    title: '서울 나만의 스팟',
    subtitle: '5개 스팟 · 지민',
    itemCount: 5,
    coverGrad: 'linear-gradient(135deg, #45D6C6 0%, #17233C 100%)',
    isOwn: true,
    isOfficial: false,
    spots: ['gyeongbok', 'seongsu', 'itaewon-danbam'],
  },
];

const BADGES = [
  { id: 'first-checkin', title: '첫 방문', icon: '🎯', earned: true, subtitle: '첫 스팟 방문 인증' },
  { id: 'tokyo-5', title: '도쿄 초심자', icon: '🗼', earned: true, subtitle: '도쿄 스팟 5곳 방문' },
  { id: 'kimi-master', title: '너의 이름은. 마스터', icon: '🌠', earned: false, subtitle: '작품 스팟 전체 완주 · 4/12', progress: 4, total: 12 },
  { id: 'golden-hour', title: '골든아워 헌터', icon: '🌅', earned: true, subtitle: '일몰 시간대 3회 인증' },
  { id: 'collection-done', title: '컬렉션 완주자', icon: '📸', earned: false, subtitle: '내 컬렉션 1개 100% 방문' },
  { id: 'seoul-10', title: '서울 애호가', icon: '🏙️', earned: false, subtitle: '서울 스팟 10곳 방문 · 3/10', progress: 3, total: 10 },
];

const NOTIFICATIONS = [
  { id: 'n1', type: 'badge', title: '새 배지 획득!', body: '도쿄 초심자 배지를 획득했어요.', time: '방금', unread: true, icon: '🗼' },
  { id: 'n2', type: 'moderation', title: '제보가 승인되었어요', body: '"성수동 붉은벽돌 골목" 이 지도에 노출됩니다.', time: '2시간 전', unread: true, icon: '✓' },
  { id: 'n3', type: 'promotion', title: '내 스팟이 검증되었어요', body: '"성수동 붉은벽돌 골목" 이 사용자 검증 단계로 승격되었습니다.', time: '어제', unread: false, icon: '★' },
  { id: 'n4', type: 'badge', title: '새 배지 획득!', body: '골든아워 헌터 배지를 획득했어요.', time: '3일 전', unread: false, icon: '🌅' },
];

const MODERATION_QUEUE = [
  { id: 'm1', type: '스팟 제보', title: '롯데월드타워 63층 스카이덱', reporter: 'user_842', time: '방금', priority: 'high' },
  { id: 'm2', type: '신고', title: '"북한산 인공암벽" — 사유지 침해', reporter: 'user_311', time: '10분 전', priority: 'high' },
  { id: 'm3', type: '스팟 제보', title: '오다이바 자유의 여신상 전망대', reporter: 'trusted_user_2', time: '25분 전', priority: 'mid' },
  { id: 'm4', type: '공식 승격', title: '홍대 걷고싶은거리 → USER_VERIFIED', reporter: '자동', time: '1시간 전', priority: 'mid' },
  { id: 'm5', type: '신고', title: '"이태원 단밤 포차 앞" 사진 부적절', reporter: 'user_142', time: '2시간 전', priority: 'low' },
  { id: 'm6', type: '스팟 제보', title: '기치조지 이노카시라 공원 벚꽃길', reporter: 'user_299', time: '3시간 전', priority: 'low' },
];

const RECENT_SEARCHES = ['후지산', '너의 이름은', '남산 야경', '스가 신사', '경복궁'];
const TRENDING = ['도쿄 야경', '벚꽃 스팟', '한강 일몰', '애니 성지', '노을 명소', '옥상 뷰'];

Object.assign(window, { CITIES, WORKS, SPOTS, COLLECTIONS, BADGES, NOTIFICATIONS, MODERATION_QUEUE, RECENT_SEARCHES, TRENDING });
